### ISSUE TITLE
Connect to Google Map API

### ISSUE THREAD

**Issue by xuantain** [xuantain/coffeeShopApp#4]
1. Create new key GoogleMap for using API
2. Get location from MapAPI with data of each coffeeShop

**Comment by cesine** [comment]
Step 1: copy the private services sample file to create your own file on your dev machine 

``` bash
$ cp app/scripts/services/privateconstants.js app/scripts/services/privateconstants_sample.js
```

Step 2: Each dev needs to get their own key and put it their private constants file. 
https://developers.google.com/maps/documentation/javascript/tutorial
